version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - kafka
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  sensor:
    stop_signal: SIGINT
    restart: on-failure
    build: ./sensor
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:29092
    networks:
      - kafka

  analyzer:
    stop_signal: SIGINT
    restart: on-failure
    build: ./analyzer
    depends_on:
      - kafka
      - sensor
    environment:
      - KAFKA_BROKER=kafka:29092
    networks:
      - kafka

  api:
    stop_signal: SIGINT
    restart: on-failure
    build: ./api
    ports:
      - 8000:8000
    volumes:
      - .:/api
    depends_on:
      - kafka
      - analyzer
      - sensor
    environment:
      - KAFKA_BROKER=kafka:29092
    networks:
      - kafka

  webapp:
    build: ./webapp
    volumes:
      - ./webapp:/webapp
    ports:
      - '3000:3000'
    depends_on:
      - kafka
      - api
    networks:
      - kafka

networks:
  kafka:
    driver: bridge
